### ISSUE TITLE
请问前端请求 socket.io.js 是如何完成响应的

### ISSUE THREAD

**Issue by yft** [careteenL/webpack-hmr#1]
您好，不好意思用 issue 向您提个问。

在调整代码过程中，发现前端请求 `socket.io.js` 时，并没有走后端的处理中间件。不知道这个资源的响应是在哪里处理的？

**Comment by yft** [comment]
看代码的时候粗心了，server 作为参数传给了 socket，请求在 socket 中进行了处理。

故事讲得很好，一看就明白了，谢谢大佬 😀

**Comment by careteenL** [comment]
> 看代码的时候粗心了，server 作为参数传给了 socket，请求在 socket 中进行了处理。
> 
> 故事讲得很好，一看就明白了，谢谢大佬 😀

一起学习😀
